version: "3.8"

services:
  reverse-proxy:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=alotaishanab@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --api.insecure=true
    # If Traefik v2.9+, you can also use Docker labels to configure these instead of command flags.

  backend:
    image: alotaishanab/ellanatek-backend:latest
    container_name: my_backend
    # Only exposed inside Docker (no host port).
    expose:
      - "5004"
    labels:
      - "traefik.enable=false"
      # If you want to route requests to /api => backend, add a router here.

  frontend:
    image: alotaishanab/ellanatek-frontend:latest
    container_name: my_frontend
    expose:
      - "80" 
    labels:
      - "traefik.enable=true"

      # 1) HTTPS router
      - "traefik.http.routers.frontend.rule=Host(`admotionsa.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

      # 2) HTTP->HTTPS redirect router
      - "traefik.http.routers.frontend-http.rule=Host(`admotionsa.com`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
