services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: alotaishanab/ellanatek-backend:latest
    container_name: my_backend
    platform: linux/amd64
    ports:
      - "5004:5004"
      - "8081:8081"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-net
    restart: unless-stopped



  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
      # - "443:443"   # Commented for local testing, no SSL locally
    networks:
      - app-net
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./certs:/etc/nginx/certs   # Commented, not needed locally
      # - ./frontend/build:/usr/share/nginx/html  # DISABLED: skipping frontend entirely
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
