version: "3.8"

services:
  backend:
    image: alotaishanab/ellanatek-backend:latest
    container_name: my_backend
    expose:
      - "5004"
    networks:
      - app-net
    restart: unless-stopped

  frontend:
    image: alotaishanab/ellanatek-frontend:latest
    container_name: my_frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-net
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
