version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    # Map container port to host
    ports:
      - "5004:5004"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./ellanatek
      dockerfile: Dockerfile
    container_name: my_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://backend:5004"
