version: "3.8"

services:
  backend:
    # Using the pre-built Docker Hub image now
    image: alotaishanab/ellanatek-backend:latest
    container_name: my_backend
    ports:
      - "5004:5004"

  frontend:
    # Using the pre-built Docker Hub image now
    image: alotaishanab/ellanatek-frontend:latest
    container_name: my_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
